Light maintenance
go-git/gcfg pull request #1
Opened 2023-01-03 17:27 UTC by MichaelMure

This PR is a form of light maintenance on this repo. Details are in each commit, but TL;DR:
- add go module
- add CI
- modernize a bit the code (remove support for go1.0 and go1.2, deprecated functions)
- make sure that the tests pass

2023-03-03 12:09 UTC, hiddeco commented on .github/test.yml
> +        run: make test-coverage
```suggestion
        run: make test-coverage

```

2023-03-06 20:46 UTC, pjbgf requested changes
A few nits to align with version on `go-git`.

2023-03-06 20:46 UTC, pjbgf commented on .github/test.yml
> +        uses: actions/setup-go@v1
```suggestion
        uses: actions/setup-go@v3
```

2023-03-06 20:46 UTC, pjbgf commented on .github/test.yml
> +        uses: actions/checkout@v2
```suggestion
        uses: actions/checkout@v3
```

2023-03-06 20:46 UTC, pjbgf commented on .github/test.yml
> +        go-version: [1.18.x, 1.19.x]
```suggestion
        go-version: [1.19.x, 1.20.x]
```

2023-03-06 20:46 UTC, pjbgf commented on go.mod
> +go 1.12
```suggestion
go 1.13
```

2023-03-07 12:24 UTC, hiddeco approved these changes
Thank you @MichaelMure :bow:

2023-03-07 12:33 UTC, MichaelMure commented
BTW, I found out about two maintained fork of `gcfg`:
- https://github.com/please-build/gcfg
- https://github.com/gravwell/gcfg

The first one apparently has a very very nice capability: being able to edit a config file without deleting the comments a user might have put there. It would be great to cherry pick those commits. See for example https://github.com/MichaelMure/git-bug/issues/1022 how that can cause problems.

2023-03-07 21:58 UTC, pjbgf approved these changes
Thank you @MichaelMure!

2023-03-07 22:00 UTC, merged

2023-03-07 22:01 UTC, pjbgf commented
@MichaelMure as for the changes in other forks, it would be better to ask the authors whether they want to upstream their changes.